# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
print([*s])

['H', 'i', ' ', 't', 'h', 'e', 'r', 'e', ' ', 'S', 'a', 'm', '!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
ydiameter = 12742

In [2]:
print("the diameter of {} is {} kilometers.".format("earth",12742))

the diameter of earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [25]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])


hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integer form 20 to 35:")
print(array)

Array of all the even integer form 20 to 35:
[20 22 24 26 28 30 32 34]


## 5. Create an array of all the even integers from 20 to 35

In [20]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35:")
print(array)

Array of all the even integers from 20 to 35:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [28]:
import pandas as pd
students=[['arivu',21],
         ['mani',35],
         ['karthi',44]]
df=pd.DataFrame(students,columns=['Name','Age'])
print(df)



     Name  Age
0   arivu   21
1    mani   35
2  karthi   44


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [31]:
import datetime
import pandas as pd
testdate=datetime.datetime.strptime("21-08-21","%d-%m-%y")
k=41
dategenerated=pd.date_range(testdate,periods=k)
print(dategenerated.strftime("%d-%m-%y"))


Index(['21-08-21', '22-08-21', '23-08-21', '24-08-21', '25-08-21', '26-08-21',
       '27-08-21', '28-08-21', '29-08-21', '30-08-21', '31-08-21', '01-09-21',
       '02-09-21', '03-09-21', '04-09-21', '05-09-21', '06-09-21', '07-09-21',
       '08-09-21', '09-09-21', '10-09-21', '11-09-21', '12-09-21', '13-09-21',
       '14-09-21', '15-09-21', '16-09-21', '17-09-21', '18-09-21', '19-09-21',
       '20-09-21', '21-09-21', '22-09-21', '23-09-21', '24-09-21', '25-09-21',
       '26-09-21', '27-09-21', '28-09-21', '29-09-21', '30-09-21'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],[2, 'bbb', 25],[3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22],[2, 'bbb', 25],[3, 'ccc', 24]]

In [19]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['Fno','char','Lno'],dtype=float)
print(df)

   Fno char   Lno
0  1.0  aaa  22.0
1  2.0  bbb  25.0
2  3.0  ccc  24.0
